spring.application.name=api-rest-mongo
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=${MONGODB_DATABASE:equipos_db}
server.address=127.0.0.1
server.port=${PORT:8092}
server.error.include-message=never
